### PR TITLE
Forbid duplicate data with labels from being ingested

### PR DESCRIPTION
**Pull request by schittarath3-rti**
This throws a form error is duplicate data with old labels in ingested through the update data pipeline. Does not affect project creation data upload.

Error shows which rows in the uploaded data contains this problem

### CODE REVIEW

**Comment by schittarath3-rti** [comment]
I think the part where it shows which rows are problem-causing is not user-friendly. 

Currently, it shows it as a csv, but pandas has a to_html function for dataframes which could look better. It does not work well with django form errors though because it shows it has the string rather than html.

**Comment by schittarath3-rti** [comment]
Current error message:
image

**Comment by schittarath3-rti** [comment]
Also what do you guys think about limiting the number of rows that is displayed? Currently, it shows all rows.

**Comment by AstridKery** [comment]
I'd say list the first 5 or 10, then just say the number of remaining differences. The error message is a bit confusing. Are you saying the data is already there and labeled, or it's there at all?

**Comment by schittarath3-rti** [comment]
Should mean that the data is there, either unlabelled or labelled.

**Pull request closed without merging**
