### PR TITLE
Npsas metadata and deuplication tests

### PR DESCRIPTION
**Pull request by schittarath3-rti**
Adds tests for metadata uploading and deduplication of data based on text, all metadata, and select metadata

### CODE REVIEW

**Comment by AstridKery** [comment]
@dsteedRTI are you comfortable taking a first pass? I think the key with this one is to think of the different options the user has when creating a project in terms of metadata and deduping, and check that we test them thoroughly.

**Comment by dsteedRTI** [comment]
@AstridKery these looked good to me on a first pass

**Comment by peridoteagle** [comment]
Pinging @AstridKery - let me know if these look good to merge

**Review by AstridKery — APPROVED** [review]
These look great! Thanks so much!

**Pull request merged**
